[build]
publish = "public"

[context.production.environment]
CORS_ALLOW_ORIGIN = "*"
CORS_ALLOW_METHODS = "GET, POST, PUT, DELETE, OPTIONS"
CORS_ALLOW_HEADERS = "Content-Type, Authorization"
CORS_ALLOW_CREDENTIALS = "true"
CORS_MAX_AGE = "3600"